<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Render partner and supporter logo grids.
 *
 * The renderer is shared by the shortcode and Elementor widget so both
 * integrations remain visually and functionally consistent.
 */
function artasia_logos_shortcode($attributes): string
{
    $attributes = shortcode_atts([
        'partner_heading'   => 'Partners',
        'supporter_heading' => 'Supporters',
        'variant'           => 'colour',
        'project_id'        => '',
    ], $attributes, 'artasia_logos');

    return artasia_render_logos([
        'partner_heading'   => (string) $attributes['partner_heading'],
        'supporter_heading' => (string) $attributes['supporter_heading'],
        'variant'           => (string) $attributes['variant'],
        'project_id'        => absint($attributes['project_id']),
    ]);
}
add_shortcode('artasia_logos', 'artasia_logos_shortcode');

function artasia_normalize_logo_variant(string $variant): string
{
    $variant = strtolower(trim($variant));

    return $variant === 'white' ? 'white' : 'colour';
}

function artasia_get_logo_grid_item(WP_Post $post, string $variant): ?array
{
    $colour_logo_id = intval(get_post_meta($post->ID, 'artasia_logo_id', true));
    $white_logo_id = intval(get_post_meta($post->ID, 'artasia_white_logo_id', true));
    $variant = artasia_normalize_logo_variant($variant);

    $logo_id = $variant === 'white' ? $white_logo_id : $colour_logo_id;
    $actual_variant = $variant;

    // Keep an incomplete record visible by falling back to its other logo.
    if (!$logo_id) {
        $logo_id = $variant === 'white' ? $colour_logo_id : $white_logo_id;
        $actual_variant = $variant === 'white' ? 'colour' : 'white';
    }

    if (!$logo_id || !wp_attachment_is_image($logo_id)) {
        return null;
    }

    $image = wp_get_attachment_image($logo_id, 'full', false, [
        'class'    => 'artasia-logo-grid__image',
        'alt'      => $post->post_title,
        'loading'  => 'lazy',
        'decoding' => 'async',
    ]);

    if (!$image) {
        return null;
    }

    return [
        'id'      => $post->ID,
        'name'    => $post->post_title,
        'image'   => $image,
        'variant' => $actual_variant,
        'website' => (string) get_post_meta($post->ID, 'artasia_website', true),
    ];
}

function artasia_get_logo_grid_items(string $post_type, string $variant, int $project_id = 0): array
{
    $posts = get_posts([
        'post_type'      => $post_type,
        'posts_per_page' => -1,
        'post_status'    => 'publish',
        'orderby'        => 'title',
        'order'          => 'ASC',
        'no_found_rows'  => true,
    ]);

    $items = [];
    foreach ($posts as $post) {
        if (
            $post_type === 'artasia_supporter'
            && $project_id
            && !in_array(
                $project_id,
                artasia_sanitize_integer_array_meta(get_post_meta($post->ID, 'artasia_supporter_project_ids', true)),
                true
            )
        ) {
            continue;
        }

        $item = artasia_get_logo_grid_item($post, $variant);
        if ($item !== null) {
            $items[] = $item;
        }
    }

    return $items;
}

function artasia_group_supporter_logo_items(array $items): array
{
    $groups = [];

    foreach ($items as $item) {
        $type = trim((string) get_post_meta($item['id'], 'artasia_supporter_type', true));
        $group_key = $type !== '' ? $type : 'Other';

        if (!isset($groups[$group_key])) {
            $groups[$group_key] = [];
        }

        $groups[$group_key][] = $item;
    }

    uksort($groups, static function (string $a, string $b): int {
        if ($a === 'Other') {
            return 1;
        }
        if ($b === 'Other') {
            return -1;
        }

        return strcasecmp($a, $b);
    });

    return $groups;
}

function artasia_render_logo_grid(array $items): void
{
    if (!$items) {
        return;
    }
    ?>
    <ul class="artasia-logo-grid">
        <?php foreach ($items as $item) : ?>
            <li class="artasia-logo-grid__item artasia-logo-grid__item--<?php echo esc_attr($item['variant']); ?>">
                <?php if ($item['website'] !== '') : ?>
                    <a class="artasia-logo-grid__link" href="<?php echo esc_url($item['website']); ?>" target="_blank" rel="noopener noreferrer">
                        <?php echo $item['image']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
                    </a>
                <?php else : ?>
                    <span class="artasia-logo-grid__link">
                        <?php echo $item['image']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php
}

function artasia_render_logos(array $args = []): string
{
    $args = wp_parse_args($args, [
        'partner_heading'   => 'Partners',
        'supporter_heading' => 'Supporters',
        'variant'           => 'colour',
        'project_id'        => 0,
    ]);

    $variant = artasia_normalize_logo_variant((string) $args['variant']);
    $project_id = absint($args['project_id']);
    if (
        $project_id
        && (
            get_post_type($project_id) !== 'artasia_project'
            || get_post_status($project_id) !== 'publish'
        )
    ) {
        return '';
    }

    $partners = artasia_get_logo_grid_items('artasia_partner', $variant);
    $supporter_groups = artasia_group_supporter_logo_items(
        artasia_get_logo_grid_items('artasia_supporter', $variant, $project_id)
    );

    if (!$partners && !$supporter_groups) {
        return '';
    }

    wp_enqueue_style('artasia-logos-shortcode');

    ob_start();
    ?>
    <section class="artasia-logo-sections artasia-logo-sections--<?php echo esc_attr($variant); ?>">
        <div class="artasia-logo-sections__inner">
            <?php if ($partners) : ?>
                <section class="artasia-logo-section artasia-logo-section--partners">
                    <h2 class="artasia-logo-section__heading"><?php echo esc_html((string) $args['partner_heading']); ?></h2>
                    <?php artasia_render_logo_grid($partners); ?>
                </section>
            <?php endif; ?>

            <?php if ($supporter_groups) : ?>
                <section class="artasia-logo-section artasia-logo-section--supporters">
                    <h2 class="artasia-logo-section__heading"><?php echo esc_html((string) $args['supporter_heading']); ?></h2>
                    <?php foreach ($supporter_groups as $type => $items) : ?>
                        <section class="artasia-logo-group">
                            <h3 class="artasia-logo-group__heading"><?php echo esc_html($type); ?></h3>
                            <?php artasia_render_logo_grid($items); ?>
                        </section>
                    <?php endforeach; ?>
                </section>
            <?php endif; ?>
        </div>
    </section>
    <?php

    return trim((string) ob_get_clean());
}
