<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Render a selected Artasia exhibition.
 *
 * The renderer is shared by the shortcode and Elementor widget so both
 * integrations display the same exhibition content.
 */
function artasia_exhibition_shortcode($attributes): string
{
    $attributes = shortcode_atts([
        'id'            => '',
        'exhibition_id' => '',
    ], $attributes, 'artasia_exhibition');

    $exhibition_id = absint($attributes['id'] ?: $attributes['exhibition_id']);

    return artasia_render_exhibition($exhibition_id);
}
add_shortcode('artasia_exhibition', 'artasia_exhibition_shortcode');

function artasia_render_exhibition(int $exhibition_id): string
{
    if (
        !$exhibition_id
        || get_post_type($exhibition_id) !== 'artasia_exhibition'
        || get_post_status($exhibition_id) !== 'publish'
    ) {
        return '';
    }

    $exhibition = get_post($exhibition_id);
    if (!$exhibition instanceof WP_Post) {
        return '';
    }

    $host_name = trim((string) get_post_meta($exhibition_id, 'artasia_exhibition_host_name', true));
    $host_url = trim((string) get_post_meta($exhibition_id, 'artasia_exhibition_host_url', true));
    $host_logo_id = absint(get_post_meta($exhibition_id, 'artasia_exhibition_host_logo_id', true));
    $description = trim((string) get_post_meta($exhibition_id, 'artasia_exhibition_description', true));
    $date_range = artasia_format_exhibition_date_range(
        (string) get_post_meta($exhibition_id, 'artasia_exhibition_start_date', true),
        (string) get_post_meta($exhibition_id, 'artasia_exhibition_end_date', true)
    );

    $host_logo = '';
    if ($host_logo_id && wp_attachment_is_image($host_logo_id)) {
        $host_logo = (string) wp_get_attachment_image($host_logo_id, 'full', false, [
            'class'    => 'artasia-exhibition__host-logo-image',
            'alt'      => $host_name ?: 'Exhibition host',
            'loading'  => 'eager',
            'decoding' => 'async',
        ]);
    }

    ob_start();
    ?>
    <article class="artasia-exhibition">
        <header class="artasia-exhibition__header<?php echo $host_logo ? ' has-host-logo' : ''; ?>">
            <?php if ($host_logo) : ?>
                <div class="artasia-exhibition__host-logo">
                    <?php if ($host_url) : ?>
                        <a href="<?php echo esc_url($host_url); ?>" target="_blank" rel="noopener noreferrer">
                            <?php echo $host_logo; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
                        </a>
                    <?php else : ?>
                        <?php echo $host_logo; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div class="artasia-exhibition__heading">
                <?php if ($host_name !== '') : ?>
                    <p class="artasia-exhibition__host-name">
                        <?php if ($host_url) : ?>
                            <a href="<?php echo esc_url($host_url); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html($host_name); ?></a>
                        <?php else : ?>
                            <?php echo esc_html($host_name); ?>
                        <?php endif; ?>
                    </p>
                <?php endif; ?>
                <h2 class="artasia-exhibition__title"><?php echo esc_html($exhibition->post_title); ?></h2>
                <?php if ($date_range !== '') : ?>
                    <p class="artasia-exhibition__date"><?php echo esc_html($date_range); ?></p>
                <?php endif; ?>
            </div>
        </header>
        <?php if ($description !== '') : ?>
            <div class="artasia-exhibition__description">
                <?php echo wp_kses_post(wpautop($description)); ?>
            </div>
        <?php endif; ?>
    </article>
    <?php

    wp_enqueue_style('artasia-exhibition-shortcode');

    return trim((string) ob_get_clean());
}
